# Generated by Django 4.1.7 on 2023-02-23 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateTimeField()),
                ('nationality', models.CharField(max_length=50)),
                ('state_of_origin', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentclass')),
            ],
        ),
    ]
