# Generated by Django 3.2.18 on 2023-05-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubject',
            name='score',
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='exam_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='test_score',
            field=models.IntegerField(default=0),
        ),
    ]
