# Generated by Django 3.2.18 on 2023-04-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name_plural': 'Classes'},
        ),
    ]
