# Generated by Django 3.2 on 2023-02-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_studentdetails_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
