# Generated by Django 3.2 on 2023-02-26 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_studentdetails_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.studentclass'),
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('class_offered', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.studentclass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.teacher')),
            ],
        ),
    ]
