# Generated by Django 3.2 on 2023-02-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20230227_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubject',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
