# Generated by Django 3.2.18 on 2023-06-08 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_picture',
            new_name='profile_image',
        ),
    ]
