# Generated by Django 3.2.18 on 2023-04-26 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230426_1346'),
        ('userauth', '0004_auto_20230426_1322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
