# Generated by Django 3.2.18 on 2023-04-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_delete_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_principal',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
