# Generated by Django 3.2.18 on 2023-04-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_auto_20230426_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='classroom',
            field=models.CharField(blank=True, choices=[('1', 'JSS1'), ('2', 'JSS2'), ('3', 'JSS3')], max_length=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
